
# =============================
# テーブル配列
# =============================
[[products]]
name = "Hammer"
sku = 738594937

[[products]]
name = "Nail"
sku = 284758393
color = "gray"

[kara]

[[karas]]
